[package]
name = "granne"
version = "0.1.0"
authors = ["Erik Larsson <erik.ie.larsson@gmail.com>"]
license = "MIT"
links = "blas"
build = "build.rs"
edition = "2018"

[dependencies]
bytes = "0.4"
byteorder = "1.2.1"
ordered-float = "0.5.0"
time = "0.1"
rand = "0.3"
rayon = "1.0"
flate2 = "0.2.19"
fnv = "1.0.6"
memmap = "0.6.2"
revord = "0.0.2"
blas = "0.20.0"
pbr = "1.0.0"
num-iter = "0.1"
clap = "2.28.0"
toml = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0.2"
slice_vector = {path = "slice_vector/"}
parking_lot = "0.7"
crossbeam = "0.3.2"
madvise = "0.1.0"
bit-vec = "0.5.0"
