[package]
name = "granne"
version = "0.1.0"
authors = ["Erik Larsson <erik.ie.larsson@gmail.com>"]
license = "MIT"

[dependencies]
arrayvec = "0.4.2"
ordered-float = "0.5.0"
time = "*"
rand = "0.3"
rayon = "0.9"
fnv = "1.0.6"
memmap = "0.6.2"
revord = "0.0.2"
rblas = "0.0.13"
pbr = "1.0.0"
num-iter = "0.1"
clap = "2.28.0"
toml = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0.2"
crossbeam = "0.3.2"
