[package]
name = "hnsw"
version = "0.1.0"
authors = ["Erik Larsson <erik.ie.larsson@gmail.com>"]

[dependencies]
arrayvec = "0.4.2"
ordered-float = "0.5.0"
time = "*"
rand = "0.3"
rayon = "0.9"
fnv = "1.0.6"
memmap = "0.6.1"
revord = "0.0.2"
rblas = "0.0.13"
pbr = "1.0.0"
num-iter = "0.1"