[build-system]
requires = [
    'setuptools',
    'setuptools_rust'
]
build-backend = 'setuptools.build_meta'

[project]
name = "cnstrc-granne"
version = "0.5.2.5.dev0"

[[tool.setuptools-rust.ext-modules]]
target = "granne"
path = "py/Cargo.toml"
binding = "RustCPython"
