[package]
name = "granne-py"
version = "0.1.0"
authors = ["Erik Larsson <erik.ie.larsson@gmail.com>"]

[lib]
name = "granne"
crate-type = ["cdylib"]

[dependencies.cpython]
version = "0.2"
default-features = false
features = ["python27-sys", "extension-module-2-7"]

[dependencies]
memmap = "0.6.2"
granne = { path = ".." }
