[package]
name = "slice_vector"
version = "0.1.0"
authors = ["Erik Larsson <erik.ie.larsson@gmail.com>"]
edition = "2018"

[dependencies]
byteorder = "1.2.1"
rayon = "1.0"
tempfile = "3.0.5"
stream-vbyte = "0.3.2"
